---
# tasks file for ubuntu-security

- name: Upgrading all OS packages
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: "[DISCOVERY] Ensure only root has UID 0"
    command: |
            awk -F: '($3=="0"){print}' /etc/passwd
    register: sys_uid_zero
    failed_when: ( ( sys_uid_zero.stdout_lines|length ) > 1 ) or ( 'root' not in sys_uid_zero.stdout )

- name: "[DISCOVERY] Check for accounts with empty passwords"
    command: |
            awk -F: '($2==""){print $1}' /etc/shadow
    register: sys_empty_pass
    failed_when: ( sys_empty_pass.stdout_lines|length ) > 0


