---
- hosts: ubuntu-boxes
  become: true
  become_method: sudo
  tasks:

    - name: "system | Upgrading all OS packages"
      apt:
        name: "*"
        state: latest
        update_cache: yes

  roles:
    - fail2ban
    - ubuntu-security
    - rkhunter
